# Generated by Django 6.1.1 on 2026-10-05 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_dataset_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(max_length=12)),
                ('symbols', models.JSONField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('batch_size', models.PositiveSmallIntegerField(default=5)),
                ('prefer_cache', models.BooleanField(default=True)),
                ('refresh_daily', models.BooleanField(default=False)),
                ('series', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=dict)),
                ('message', models.TextField(blank=True)),
                ('busy_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
