# Generated by Django 6.1.1 on 2026-10-05 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_fetchrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('interface', models.CharField(choices=[('portfolio', 'Portfolio'), ('research', 'Research')], max_length=12)),
                ('entry_point', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('sources', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('dataset_digest', models.CharField(blank=True, max_length=64)),
                ('window', models.CharField(blank=True, max_length=12)),
                ('holdout_claim', models.BooleanField(default=False)),
                ('result', models.JSONField(default=dict)),
                ('runtime', models.JSONField(default=dict)),
                ('artifacts', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('notes', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.dataset')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.evaluation')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lab.researchrun')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.strategyrevision')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('holdout_claim', True)), fields=('owner', 'workspace', 'dataset_digest'), name='one_research_holdout_opening'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('owner', 'workspace', 'idempotency_key'), name='one_research_idempotency_key')],
            },
        ),
    ]
